# Generated by Django 4.2.11 on 2024-05-04 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_metrics', '0002_alter_purchaseorder_po_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalperformance',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('completed', 'completed'), ('canceled', 'canceled')], default='pending', max_length=50),
        ),
        migrations.AddIndex(
            model_name='historicalperformance',
            index=models.Index(fields=['date'], name='vendor_metr_date_6df72e_idx'),
        ),
    ]
